runtime: php55
api_version: 1

handlers:

- url: /stylesheet
  static_dir: stylesheet

- url: /
  script: index.php

- url: /header.php
  script: header.php

- url: /index.php
  script: index.php

- url: /buffer.php
  script: buffer.php

- url: /nickel_buffer.php
  script: nickel_buffer.php

- url: /condition.php
  script: condition.php

- url: /LIC_primers.php
  script: LIC_primers.php

- url: /gibson.php
  script: gibson.php

- url: /contact.php
  script: contact.php

- url: /.*
  script: not_found.php