runtime: php55
api_version: 1

handlers:

- url: /stylesheet
  static_dir: stylesheet

- url: /
  script: index.php

- url: /index.php
  script: index.php

- url: /LIC_primers.php
  script: LIC_primers.php

- url: /.*
  script: not_found.php