runtime: php55
api_version: 1

handlers:

- url: /stylesheet
  static_dir: stylesheet

- url: /lib
  static_dir: lib

- url: /db
  static_dir: db

- url: /
  script: index.php

- url: /lib/header.php
  script: /lib/header.php

- url: /lib/header_buffer.php
  script: /lib/header_buffer.php

- url: /index.php
  script: index.php

- url: /buffer.php
  script: buffer.php

- url: /nickel_buffer.php
  script: nickel_buffer.php

- url: /two_ph.php
  script: two_ph.php

- url: /condition.php
  script: condition.php

- url: /LIC_primers.php
  script: LIC_primers.php

- url: /gibson.php
  script: gibson.php

- url: /contact.php
  script: contact.php

- url: /.*
  script: not_found.php