runtime: php55
api_version: 1

handlers:

- url: /stylesheet
  static_dir: stylesheet

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: db/\1
  upload: db/(.*\.xml)
  expiration: "1h"

- url: /header.php
  script: header.php

- url: /header_buffer.php
  script: header_buffer.php

- url: /
  script: index.php

- url: /index.php
  script: index.php

- url: /buffer.php
  script: buffer.php

- url: /nickel_buffer.php
  script: nickel_buffer.php

- url: /two_ph.php
  script: two_ph.php

- url: /bradford.php
  script: bradford.php

- url: /convert_protein.php
  script: convert_protein.php

- url: /dilution.php
  script: dilution.php

- url: /gel_buffer.php
  script: gel_buffer.php

- url: /condition.php
  script: condition.php

- url: /LIC_primers.php
  script: LIC_primers.php

- url: /gibson.php
  script: gibson.php

- url: /gibson_multi.php
  script: gibson_multi.php

- url: /contact.php
  script: contact.php

- url: /.*
  script: not_found.php